### ISSUE TITLE
Allow setting values for URL params

### ISSUE THREAD

**Issue by rmccue** [WP-API/rest-api-console#20]
The dotcom API allows setting values for these with `$var` in the URL. I changed the route parser to take care of parsing it out of the route, but it seems like it won't display an editor unless there's parameter documentation for it too (which is set in [app.js](https://github.com/WP-API/rest-api-console/blob/master/lib/app.js#L77-L91)).

**Comment by obenland** [comment]
Fixed in b13ddf1e66f6d00833490554fc850eb52ba2f96d
