### ISSUE TITLE
readme.txt WordPress REST API  plugin link

### ISSUE THREAD

**Issue by ntwb** [WP-API/rest-api-console#29]
The `readme.txt` is currently linking 'WordPress REST API ' to non existent `https://wordpress.org/plugin/rest-api/`

There is @johnbillion's at `https://wordpress.org/plugins/rest-api/`

v1 is here https://wordpress.org/plugins/json-rest-api/, if that's going to be updated to v2 that's what we want, if not a link to the new v2 plugin is needed ;)

https://github.com/WP-API/rest-api-console/blob/master/lib/readme.txt

**Comment by rmccue** [comment]
`rest-api` will be v2 in the next day or so, we're working on getting that set up at the moment. :)

**Comment by ntwb** [comment]
You'll still need that `s`, `plugins`, not `plugin` ;)

**Comment by rmccue** [comment]
Heh, good catch on that one :)

**Comment by ntwb** [comment]
:+1:
