### ISSUE TITLE
404s due to paths being appended onto endpoint

### ISSUE THREAD

**Issue by johnbillion** [WP-API/rest-api-console#31]
This plugin currently does not work because the URL paths that are generated contain a double slash and result in a 404. This happens because the route paths contain a leading slash and they get appended onto the REST API endpoint which contain a trailing slash.

Most likely caused by https://github.com/WP-API/WP-API/pull/1426

See https://core.trac.wordpress.org/ticket/34302

**Comment by rmccue** [comment]
This was actually fixed in cf73d647dbce4d7e6f27a703884136546e6c47ff but never pushed to W.org. Fixed.
